version: "3.7"
services:
    web:
        image: cupcakearmy/static
        ports:
          - "5083:80"
        networks:
          - web
        volumes:
          - ./static:/srv:ro
        restart: unless-stopped
        labels:
          traefik.enable: true
          traefik.port: 5083
          traefik.frontend.rule: "Host:acab.haj.gf"
          traefik.frontend.redirect.entryPoint: "https"
          traefik.docker.network: web

networks:
  web:
    external: true