version: '3.3'
services:
    web:
        image: nginx:latest
        ports:
          - "5079:80"
        networks:
          - web
          - internal
        volumes:
          - ./code:/var/www/html
          - ./default.conf:/etc/nginx/conf.d/default.conf
        restart: always
        labels:
          traefik.enable: true
          traefik.port: 5079
          traefik.frontend.rule: "Host:acab.haj.gf"
          traefik.frontend.redirect.entryPoint: "https"
          traefik.docker.network: web
    php-fpm:
        image: php:8-fpm
        networks:
          - internal
        volumes:
          - ./code:/var/www/html

networks:
  web:
    external: true
  internal:
    driver: bridge